services:
  postgres:
    container_name: postgres_container
    image: postgres:14.1
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - postgres:/data/postgres

  # elasticsearch:
  #   container_name: elasticsearch_container
  #   image: elasticsearch:7.17.0
  #   ports:
  #     - "9200:9200"
  #   restart: unless-stopped
  #   volumes:
  #     - elasticsearch:/data/elasticsearch

secrets:
  postgres_user:
    file: ./.secrets/postgres_user.txt
  postgres_password:
    file: ./.secrets/postgres_password.txt
volumes:
  postgres:
