services:
  postgres:
    container_name: postgres_container
    image: postgres:14.1
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - postgres:/data/postgres

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin

secrets:
  postgres_user:
    file: ./.secrets/postgres_user.txt
  postgres_password:
    file: ./.secrets/postgres_password.txt
volumes:
  postgres:
  # pgadmin:
