services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - postgres:/data/postgres

  myweb:
    container_name: myweb
    image: myweb:v1
    ports:
      - 5000:80
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${LOGLOCATION}
        target: /var/log
    environment:
      MyWeb_PostgresDbSettings__Username: ${MyWeb_PostgresDbSettings__Username}
      MyWeb_PostgresDbSettings__Password: ${MyWeb_PostgresDbSettings__Password}
      MyWeb_EmailSettings__Password: ${MyWeb_EmailSettings__Password}

  frontend:
    container_name: frontend
    image: frontend:v1
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${LOGLOCATION}/nginx
        target: /var/log/nginx

  # elasticsearch:
  #   container_name: elasticsearch
  #   image: elasticsearch:7.17.0
  #   environment:
  #     discovery.type: "single-node"
  #     # xpack.security.enabled: "true"
  #     # ELASTIC_PASSWORD_FILE: /run/secrets/elasticsearch_password
  #   ports:
  #     - 9200:9200
  #   restart: unless-stopped
  #   volumes:
  #     - elasticsearch:/data/elasticsearch

  # kibana:
  #   container_name: kibana
  #   image: kibana:7.17.0
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch

secrets:
  postgres_user:
    file: ./.secrets/postgres_user.txt
  postgres_password:
    file: ./.secrets/postgres_password.txt
  # elasticsearch_password:
  #   file: ./.secrets/elasticsearch_password.txt

volumes:
  postgres:
  # elasticsearch:
